/*
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailslurp.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AccountBounceBlockDto
 */
public class AccountBounceBlockDtoTest {
    private final AccountBounceBlockDto model = new AccountBounceBlockDto();

    /**
     * Model tests for AccountBounceBlockDto
     */
    @Test
    public void testAccountBounceBlockDto() {
        // TODO: test AccountBounceBlockDto
    }

    /**
     * Test the property 'isFrozen'
     */
    @Test
    public void isFrozenTest() {
        // TODO: test isFrozen
    }

    /**
     * Test the property 'isSendingBlocked'
     */
    @Test
    public void isSendingBlockedTest() {
        // TODO: test isSendingBlocked
    }

    /**
     * Test the property 'bounceCount'
     */
    @Test
    public void bounceCountTest() {
        // TODO: test bounceCount
    }

    /**
     * Test the property 'bounceCountToday'
     */
    @Test
    public void bounceCountTodayTest() {
        // TODO: test bounceCountToday
    }

    /**
     * Test the property 'maximumDailyBounces'
     */
    @Test
    public void maximumDailyBouncesTest() {
        // TODO: test maximumDailyBounces
    }

    /**
     * Test the property 'maximumAccountBounces'
     */
    @Test
    public void maximumAccountBouncesTest() {
        // TODO: test maximumAccountBounces
    }

}
