/*
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailslurp.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CheckDomainMonitorResults
 */
public class CheckDomainMonitorResultsTest {
    private final CheckDomainMonitorResults model = new CheckDomainMonitorResults();

    /**
     * Model tests for CheckDomainMonitorResults
     */
    @Test
    public void testCheckDomainMonitorResults() {
        // TODO: test CheckDomainMonitorResults
    }

    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'healthScore'
     */
    @Test
    public void healthScoreTest() {
        // TODO: test healthScore
    }

    /**
     * Test the property 'totalChecks'
     */
    @Test
    public void totalChecksTest() {
        // TODO: test totalChecks
    }

    /**
     * Test the property 'passingChecks'
     */
    @Test
    public void passingChecksTest() {
        // TODO: test passingChecks
    }

    /**
     * Test the property 'failingChecks'
     */
    @Test
    public void failingChecksTest() {
        // TODO: test failingChecks
    }

    /**
     * Test the property 'spfOk'
     */
    @Test
    public void spfOkTest() {
        // TODO: test spfOk
    }

    /**
     * Test the property 'dmarcOk'
     */
    @Test
    public void dmarcOkTest() {
        // TODO: test dmarcOk
    }

    /**
     * Test the property 'dmarcEnforced'
     */
    @Test
    public void dmarcEnforcedTest() {
        // TODO: test dmarcEnforced
    }

    /**
     * Test the property 'mxOk'
     */
    @Test
    public void mxOkTest() {
        // TODO: test mxOk
    }

    /**
     * Test the property 'insights'
     */
    @Test
    public void insightsTest() {
        // TODO: test insights
    }

    /**
     * Test the property 'errorMessage'
     */
    @Test
    public void errorMessageTest() {
        // TODO: test errorMessage
    }

}
