/*
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailslurp.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EmailAnalysis
 */
public class EmailAnalysisTest {
    private final EmailAnalysis model = new EmailAnalysis();

    /**
     * Model tests for EmailAnalysis
     */
    @Test
    public void testEmailAnalysis() {
        // TODO: test EmailAnalysis
    }

    /**
     * Test the property 'dkimVerdict'
     */
    @Test
    public void dkimVerdictTest() {
        // TODO: test dkimVerdict
    }

    /**
     * Test the property 'dmarcVerdict'
     */
    @Test
    public void dmarcVerdictTest() {
        // TODO: test dmarcVerdict
    }

    /**
     * Test the property 'spamVerdict'
     */
    @Test
    public void spamVerdictTest() {
        // TODO: test spamVerdict
    }

    /**
     * Test the property 'spfVerdict'
     */
    @Test
    public void spfVerdictTest() {
        // TODO: test spfVerdict
    }

    /**
     * Test the property 'virusVerdict'
     */
    @Test
    public void virusVerdictTest() {
        // TODO: test virusVerdict
    }

}
