/*
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailslurp.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MissedEmailDto
 */
public class MissedEmailDtoTest {
    private final MissedEmailDto model = new MissedEmailDto();

    /**
     * Model tests for MissedEmailDto
     */
    @Test
    public void testMissedEmailDto() {
        // TODO: test MissedEmailDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'bodyExcerpt'
     */
    @Test
    public void bodyExcerptTest() {
        // TODO: test bodyExcerpt
    }

    /**
     * Test the property 'attachmentCount'
     */
    @Test
    public void attachmentCountTest() {
        // TODO: test attachmentCount
    }

    /**
     * Test the property 'from'
     */
    @Test
    public void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'rawUrl'
     */
    @Test
    public void rawUrlTest() {
        // TODO: test rawUrl
    }

    /**
     * Test the property 'rawKey'
     */
    @Test
    public void rawKeyTest() {
        // TODO: test rawKey
    }

    /**
     * Test the property 'rawBucket'
     */
    @Test
    public void rawBucketTest() {
        // TODO: test rawBucket
    }

    /**
     * Test the property 'canRestore'
     */
    @Test
    public void canRestoreTest() {
        // TODO: test canRestore
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'cc'
     */
    @Test
    public void ccTest() {
        // TODO: test cc
    }

    /**
     * Test the property 'bcc'
     */
    @Test
    public void bccTest() {
        // TODO: test bcc
    }

    /**
     * Test the property 'inboxIds'
     */
    @Test
    public void inboxIdsTest() {
        // TODO: test inboxIds
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
