/*
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailslurp.apis;

import com.mailslurp.clients.ApiException;
import com.mailslurp.models.ExportLink;
import com.mailslurp.models.ExportOptions;
import java.time.OffsetDateTime;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExportControllerApi
 */
@Ignore
public class ExportControllerApiTest {

    private final ExportControllerApi api = new ExportControllerApi();

    
    /**
     * Export inboxes link callable via browser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void exportEntitiesTest() throws ApiException {
        String apiKey = null;
        String exportType = null;
        String outputFormat = null;
        OffsetDateTime createdEarliestTime = null;
        OffsetDateTime createdOldestTime = null;
        Boolean excludePreviouslyExported = null;
        String filter = null;
        String listSeparatorToken = null;
        byte[] response = api.exportEntities(apiKey, exportType, outputFormat, createdEarliestTime, createdOldestTime, excludePreviouslyExported, filter, listSeparatorToken);

        // TODO: test validations
    }
    
    /**
     * Get export link
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getExportLinkTest() throws ApiException {
        String exportType = null;
        ExportOptions exportOptions = null;
        String apiKey = null;
        ExportLink response = api.getExportLink(exportType, exportOptions, apiKey);

        // TODO: test validations
    }
    
}
