/*
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailslurp.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mailslurp.models.EmailHeaderAnalysisSummary;
import com.mailslurp.models.EmailHeaderReceivedHop;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mailslurp.clients.JSON;

/**
 * AnalyzeEmailHeadersResults
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T21:23:14.986223021Z[Etc/UTC]", comments = "Generator version: 7.13.0")
public class AnalyzeEmailHeadersResults {
  public static final String SERIALIZED_NAME_SUMMARY = "summary";
  @SerializedName(SERIALIZED_NAME_SUMMARY)
  @javax.annotation.Nonnull
  private EmailHeaderAnalysisSummary summary;

  public static final String SERIALIZED_NAME_RECEIVED_PATH = "receivedPath";
  @SerializedName(SERIALIZED_NAME_RECEIVED_PATH)
  @javax.annotation.Nonnull
  private List<EmailHeaderReceivedHop> receivedPath = new ArrayList<>();

  public static final String SERIALIZED_NAME_PARSED_HEADERS = "parsedHeaders";
  @SerializedName(SERIALIZED_NAME_PARSED_HEADERS)
  @javax.annotation.Nonnull
  private Map<String, List<String>> parsedHeaders = new HashMap<>();

  public static final String SERIALIZED_NAME_WARNINGS = "warnings";
  @SerializedName(SERIALIZED_NAME_WARNINGS)
  @javax.annotation.Nonnull
  private List<String> warnings = new ArrayList<>();

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  @javax.annotation.Nonnull
  private List<String> errors = new ArrayList<>();

  public AnalyzeEmailHeadersResults() {
  }

  public AnalyzeEmailHeadersResults summary(@javax.annotation.Nonnull EmailHeaderAnalysisSummary summary) {
    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   * @return summary
   */
  @javax.annotation.Nonnull
  public EmailHeaderAnalysisSummary getSummary() {
    return summary;
  }

  public void setSummary(@javax.annotation.Nonnull EmailHeaderAnalysisSummary summary) {
    this.summary = summary;
  }


  public AnalyzeEmailHeadersResults receivedPath(@javax.annotation.Nonnull List<EmailHeaderReceivedHop> receivedPath) {
    this.receivedPath = receivedPath;
    return this;
  }

  public AnalyzeEmailHeadersResults addReceivedPathItem(EmailHeaderReceivedHop receivedPathItem) {
    if (this.receivedPath == null) {
      this.receivedPath = new ArrayList<>();
    }
    this.receivedPath.add(receivedPathItem);
    return this;
  }

  /**
   * Get receivedPath
   * @return receivedPath
   */
  @javax.annotation.Nonnull
  public List<EmailHeaderReceivedHop> getReceivedPath() {
    return receivedPath;
  }

  public void setReceivedPath(@javax.annotation.Nonnull List<EmailHeaderReceivedHop> receivedPath) {
    this.receivedPath = receivedPath;
  }


  public AnalyzeEmailHeadersResults parsedHeaders(@javax.annotation.Nonnull Map<String, List<String>> parsedHeaders) {
    this.parsedHeaders = parsedHeaders;
    return this;
  }

  public AnalyzeEmailHeadersResults putParsedHeadersItem(String key, List<String> parsedHeadersItem) {
    if (this.parsedHeaders == null) {
      this.parsedHeaders = new HashMap<>();
    }
    this.parsedHeaders.put(key, parsedHeadersItem);
    return this;
  }

  /**
   * Get parsedHeaders
   * @return parsedHeaders
   */
  @javax.annotation.Nonnull
  public Map<String, List<String>> getParsedHeaders() {
    return parsedHeaders;
  }

  public void setParsedHeaders(@javax.annotation.Nonnull Map<String, List<String>> parsedHeaders) {
    this.parsedHeaders = parsedHeaders;
  }


  public AnalyzeEmailHeadersResults warnings(@javax.annotation.Nonnull List<String> warnings) {
    this.warnings = warnings;
    return this;
  }

  public AnalyzeEmailHeadersResults addWarningsItem(String warningsItem) {
    if (this.warnings == null) {
      this.warnings = new ArrayList<>();
    }
    this.warnings.add(warningsItem);
    return this;
  }

  /**
   * Get warnings
   * @return warnings
   */
  @javax.annotation.Nonnull
  public List<String> getWarnings() {
    return warnings;
  }

  public void setWarnings(@javax.annotation.Nonnull List<String> warnings) {
    this.warnings = warnings;
  }


  public AnalyzeEmailHeadersResults errors(@javax.annotation.Nonnull List<String> errors) {
    this.errors = errors;
    return this;
  }

  public AnalyzeEmailHeadersResults addErrorsItem(String errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * Get errors
   * @return errors
   */
  @javax.annotation.Nonnull
  public List<String> getErrors() {
    return errors;
  }

  public void setErrors(@javax.annotation.Nonnull List<String> errors) {
    this.errors = errors;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnalyzeEmailHeadersResults analyzeEmailHeadersResults = (AnalyzeEmailHeadersResults) o;
    return Objects.equals(this.summary, analyzeEmailHeadersResults.summary) &&
        Objects.equals(this.receivedPath, analyzeEmailHeadersResults.receivedPath) &&
        Objects.equals(this.parsedHeaders, analyzeEmailHeadersResults.parsedHeaders) &&
        Objects.equals(this.warnings, analyzeEmailHeadersResults.warnings) &&
        Objects.equals(this.errors, analyzeEmailHeadersResults.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(summary, receivedPath, parsedHeaders, warnings, errors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnalyzeEmailHeadersResults {\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    receivedPath: ").append(toIndentedString(receivedPath)).append("\n");
    sb.append("    parsedHeaders: ").append(toIndentedString(parsedHeaders)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("summary");
    openapiFields.add("receivedPath");
    openapiFields.add("parsedHeaders");
    openapiFields.add("warnings");
    openapiFields.add("errors");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("summary");
    openapiRequiredFields.add("receivedPath");
    openapiRequiredFields.add("parsedHeaders");
    openapiRequiredFields.add("warnings");
    openapiRequiredFields.add("errors");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AnalyzeEmailHeadersResults
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException { if (true) { return; }
      if (jsonElement == null) {
        if (!AnalyzeEmailHeadersResults.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AnalyzeEmailHeadersResults is not found in the empty JSON string", AnalyzeEmailHeadersResults.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AnalyzeEmailHeadersResults.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AnalyzeEmailHeadersResults` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AnalyzeEmailHeadersResults.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `summary`
      EmailHeaderAnalysisSummary.validateJsonElement(jsonObj.get("summary"));
      // ensure the json data is an array
      if (!jsonObj.get("receivedPath").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `receivedPath` to be an array in the JSON string but got `%s`", jsonObj.get("receivedPath").toString()));
      }

      JsonArray jsonArrayreceivedPath = jsonObj.getAsJsonArray("receivedPath");
      // validate the required field `receivedPath` (array)
      for (int i = 0; i < jsonArrayreceivedPath.size(); i++) {
        EmailHeaderReceivedHop.validateJsonElement(jsonArrayreceivedPath.get(i));
      };
      // ensure the required json array is present
      if (jsonObj.get("warnings") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("warnings").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `warnings` to be an array in the JSON string but got `%s`", jsonObj.get("warnings").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("errors") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("errors").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `errors` to be an array in the JSON string but got `%s`", jsonObj.get("errors").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AnalyzeEmailHeadersResults.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AnalyzeEmailHeadersResults' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AnalyzeEmailHeadersResults> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AnalyzeEmailHeadersResults.class));

       return (TypeAdapter<T>) new TypeAdapter<AnalyzeEmailHeadersResults>() {
           @Override
           public void write(JsonWriter out, AnalyzeEmailHeadersResults value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AnalyzeEmailHeadersResults read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AnalyzeEmailHeadersResults given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AnalyzeEmailHeadersResults
   * @throws IOException if the JSON string is invalid with respect to AnalyzeEmailHeadersResults
   */
  public static AnalyzeEmailHeadersResults fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AnalyzeEmailHeadersResults.class);
  }

  /**
   * Convert an instance of AnalyzeEmailHeadersResults to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

