/*
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailslurp.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mailslurp.models.CampaignProbeDto;
import com.mailslurp.models.CampaignProbeRunDto;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mailslurp.clients.JSON;

/**
 * CampaignProbeRunNowResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-05T23:49:50.390480635Z[Etc/UTC]", comments = "Generator version: 7.13.0")
public class CampaignProbeRunNowResult {
  public static final String SERIALIZED_NAME_PROBE = "probe";
  @SerializedName(SERIALIZED_NAME_PROBE)
  @javax.annotation.Nonnull
  private CampaignProbeDto probe;

  public static final String SERIALIZED_NAME_RUN = "run";
  @SerializedName(SERIALIZED_NAME_RUN)
  @javax.annotation.Nonnull
  private CampaignProbeRunDto run;

  public CampaignProbeRunNowResult() {
  }

  public CampaignProbeRunNowResult probe(@javax.annotation.Nonnull CampaignProbeDto probe) {
    this.probe = probe;
    return this;
  }

  /**
   * Get probe
   * @return probe
   */
  @javax.annotation.Nonnull
  public CampaignProbeDto getProbe() {
    return probe;
  }

  public void setProbe(@javax.annotation.Nonnull CampaignProbeDto probe) {
    this.probe = probe;
  }


  public CampaignProbeRunNowResult run(@javax.annotation.Nonnull CampaignProbeRunDto run) {
    this.run = run;
    return this;
  }

  /**
   * Get run
   * @return run
   */
  @javax.annotation.Nonnull
  public CampaignProbeRunDto getRun() {
    return run;
  }

  public void setRun(@javax.annotation.Nonnull CampaignProbeRunDto run) {
    this.run = run;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CampaignProbeRunNowResult campaignProbeRunNowResult = (CampaignProbeRunNowResult) o;
    return Objects.equals(this.probe, campaignProbeRunNowResult.probe) &&
        Objects.equals(this.run, campaignProbeRunNowResult.run);
  }

  @Override
  public int hashCode() {
    return Objects.hash(probe, run);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CampaignProbeRunNowResult {\n");
    sb.append("    probe: ").append(toIndentedString(probe)).append("\n");
    sb.append("    run: ").append(toIndentedString(run)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("probe");
    openapiFields.add("run");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("probe");
    openapiRequiredFields.add("run");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CampaignProbeRunNowResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException { if (true) { return; }
      if (jsonElement == null) {
        if (!CampaignProbeRunNowResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CampaignProbeRunNowResult is not found in the empty JSON string", CampaignProbeRunNowResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CampaignProbeRunNowResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CampaignProbeRunNowResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CampaignProbeRunNowResult.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `probe`
      CampaignProbeDto.validateJsonElement(jsonObj.get("probe"));
      // validate the required field `run`
      CampaignProbeRunDto.validateJsonElement(jsonObj.get("run"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CampaignProbeRunNowResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CampaignProbeRunNowResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CampaignProbeRunNowResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CampaignProbeRunNowResult.class));

       return (TypeAdapter<T>) new TypeAdapter<CampaignProbeRunNowResult>() {
           @Override
           public void write(JsonWriter out, CampaignProbeRunNowResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CampaignProbeRunNowResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CampaignProbeRunNowResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CampaignProbeRunNowResult
   * @throws IOException if the JSON string is invalid with respect to CampaignProbeRunNowResult
   */
  public static CampaignProbeRunNowResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CampaignProbeRunNowResult.class);
  }

  /**
   * Convert an instance of CampaignProbeRunNowResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

