/*
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailslurp.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GetOrCreateSamlUserOptions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-08T04:22:46.318Z[GMT]")
public class GetOrCreateSamlUserOptions {
  public static final String SERIALIZED_NAME_ISSUER = "issuer";
  @SerializedName(SERIALIZED_NAME_ISSUER)
  private String issuer;

  public static final String SERIALIZED_NAME_NAME_ID = "nameId";
  @SerializedName(SERIALIZED_NAME_NAME_ID)
  private String nameId;

  public static final String SERIALIZED_NAME_NAME_ID_FORMAT = "nameIdFormat";
  @SerializedName(SERIALIZED_NAME_NAME_ID_FORMAT)
  private String nameIdFormat;


  public GetOrCreateSamlUserOptions issuer(String issuer) {
    
    this.issuer = issuer;
    return this;
  }

   /**
   * Get issuer
   * @return issuer
  **/
  @ApiModelProperty(required = true, value = "")

  public String getIssuer() {
    return issuer;
  }


  public void setIssuer(String issuer) {
    this.issuer = issuer;
  }


  public GetOrCreateSamlUserOptions nameId(String nameId) {
    
    this.nameId = nameId;
    return this;
  }

   /**
   * Get nameId
   * @return nameId
  **/
  @ApiModelProperty(required = true, value = "")

  public String getNameId() {
    return nameId;
  }


  public void setNameId(String nameId) {
    this.nameId = nameId;
  }


  public GetOrCreateSamlUserOptions nameIdFormat(String nameIdFormat) {
    
    this.nameIdFormat = nameIdFormat;
    return this;
  }

   /**
   * Get nameIdFormat
   * @return nameIdFormat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNameIdFormat() {
    return nameIdFormat;
  }


  public void setNameIdFormat(String nameIdFormat) {
    this.nameIdFormat = nameIdFormat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetOrCreateSamlUserOptions getOrCreateSamlUserOptions = (GetOrCreateSamlUserOptions) o;
    return Objects.equals(this.issuer, getOrCreateSamlUserOptions.issuer) &&
        Objects.equals(this.nameId, getOrCreateSamlUserOptions.nameId) &&
        Objects.equals(this.nameIdFormat, getOrCreateSamlUserOptions.nameIdFormat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issuer, nameId, nameIdFormat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetOrCreateSamlUserOptions {\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("    nameId: ").append(toIndentedString(nameId)).append("\n");
    sb.append("    nameIdFormat: ").append(toIndentedString(nameIdFormat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

