/*
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailslurp.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mailslurp.clients.JSON;

/**
 * Options for importing a raw RFC822/MIME email into a specific inbox. V1 supports MIME-family formats such as &#x60;.eml&#x60;, &#x60;message/rfc822&#x60;, and raw MIME bytes. Outlook &#x60;.msg&#x60;, &#x60;mbox&#x60;, and &#x60;maildir&#x60; are not supported in V1.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-31T10:11:56.546713700Z[Etc/UTC]", comments = "Generator version: 7.13.0")
public class ImportEmailOptions {
  public static final String SERIALIZED_NAME_RAW_EMAIL_BASE64 = "rawEmailBase64";
  @SerializedName(SERIALIZED_NAME_RAW_EMAIL_BASE64)
  @javax.annotation.Nonnull
  private String rawEmailBase64;

  public static final String SERIALIZED_NAME_EXTERNAL_ID = "externalId";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_ID)
  @javax.annotation.Nullable
  private String externalId;

  public static final String SERIALIZED_NAME_RUN_PIPELINE = "runPipeline";
  @SerializedName(SERIALIZED_NAME_RUN_PIPELINE)
  @javax.annotation.Nullable
  private Boolean runPipeline = false;

  public static final String SERIALIZED_NAME_OVERRIDE_MESSAGE_ID = "overrideMessageId";
  @SerializedName(SERIALIZED_NAME_OVERRIDE_MESSAGE_ID)
  @javax.annotation.Nullable
  private Boolean overrideMessageId = true;

  public ImportEmailOptions() {
  }

  public ImportEmailOptions rawEmailBase64(@javax.annotation.Nonnull String rawEmailBase64) {
    this.rawEmailBase64 = rawEmailBase64;
    return this;
  }

  /**
   * Base64 encoded RFC822/MIME email contents. This should be the full raw email including headers and body, such as the bytes from an &#x60;.eml&#x60; file.
   * @return rawEmailBase64
   */
  @javax.annotation.Nonnull
  public String getRawEmailBase64() {
    return rawEmailBase64;
  }

  public void setRawEmailBase64(@javax.annotation.Nonnull String rawEmailBase64) {
    this.rawEmailBase64 = rawEmailBase64;
  }


  public ImportEmailOptions externalId(@javax.annotation.Nullable String externalId) {
    this.externalId = externalId;
    return this;
  }

  /**
   * Optional external identifier for the imported email source. Useful for correlating imports back to another system.
   * @return externalId
   */
  @javax.annotation.Nullable
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(@javax.annotation.Nullable String externalId) {
    this.externalId = externalId;
  }


  public ImportEmailOptions runPipeline(@javax.annotation.Nullable Boolean runPipeline) {
    this.runPipeline = runPipeline;
    return this;
  }

  /**
   * When true the normal inbound receive pipeline runs after persistence, including automations, webhooks, transformers, forwarders, repliers, and related fanout. When false the email is stored only.
   * @return runPipeline
   */
  @javax.annotation.Nullable
  public Boolean getRunPipeline() {
    return runPipeline;
  }

  public void setRunPipeline(@javax.annotation.Nullable Boolean runPipeline) {
    this.runPipeline = runPipeline;
  }


  public ImportEmailOptions overrideMessageId(@javax.annotation.Nullable Boolean overrideMessageId) {
    this.overrideMessageId = overrideMessageId;
    return this;
  }

  /**
   * When true MailSlurp rewrites the MIME &#x60;Message-ID&#x60; header before storing and parsing the email so imported messages do not collide with existing message identities.
   * @return overrideMessageId
   */
  @javax.annotation.Nullable
  public Boolean getOverrideMessageId() {
    return overrideMessageId;
  }

  public void setOverrideMessageId(@javax.annotation.Nullable Boolean overrideMessageId) {
    this.overrideMessageId = overrideMessageId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImportEmailOptions importEmailOptions = (ImportEmailOptions) o;
    return Objects.equals(this.rawEmailBase64, importEmailOptions.rawEmailBase64) &&
        Objects.equals(this.externalId, importEmailOptions.externalId) &&
        Objects.equals(this.runPipeline, importEmailOptions.runPipeline) &&
        Objects.equals(this.overrideMessageId, importEmailOptions.overrideMessageId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(rawEmailBase64, externalId, runPipeline, overrideMessageId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImportEmailOptions {\n");
    sb.append("    rawEmailBase64: ").append(toIndentedString(rawEmailBase64)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    runPipeline: ").append(toIndentedString(runPipeline)).append("\n");
    sb.append("    overrideMessageId: ").append(toIndentedString(overrideMessageId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("rawEmailBase64");
    openapiFields.add("externalId");
    openapiFields.add("runPipeline");
    openapiFields.add("overrideMessageId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("rawEmailBase64");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ImportEmailOptions
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException { if (true) { return; }
      if (jsonElement == null) {
        if (!ImportEmailOptions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ImportEmailOptions is not found in the empty JSON string", ImportEmailOptions.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ImportEmailOptions.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ImportEmailOptions` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ImportEmailOptions.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("rawEmailBase64").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rawEmailBase64` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rawEmailBase64").toString()));
      }
      if ((jsonObj.get("externalId") != null && !jsonObj.get("externalId").isJsonNull()) && !jsonObj.get("externalId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `externalId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("externalId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ImportEmailOptions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ImportEmailOptions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ImportEmailOptions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ImportEmailOptions.class));

       return (TypeAdapter<T>) new TypeAdapter<ImportEmailOptions>() {
           @Override
           public void write(JsonWriter out, ImportEmailOptions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ImportEmailOptions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ImportEmailOptions given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ImportEmailOptions
   * @throws IOException if the JSON string is invalid with respect to ImportEmailOptions
   */
  public static ImportEmailOptions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ImportEmailOptions.class);
  }

  /**
   * Convert an instance of ImportEmailOptions to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

