/*
 * MailSlurp API
 * ## Introduction  [MailSlurp](https://www.mailslurp.com) is an Email API for developers and QA testers. It let's users: - create emails addresses on demand - receive emails and attachments in code - send templated HTML emails  ## About  This page contains the REST API documentation for MailSlurp. All requests require API Key authentication passed as an `x-api-key` header.  Create an account to [get your free API Key](https://app.mailslurp.com/sign-up/).  ## Resources - 🔑 [Get API Key](https://app.mailslurp.com/sign-up/)                    - 🎓 [Developer Portal](https://www.mailslurp.com/docs/)           - 📦 [Library SDKs](https://www.mailslurp.com/docs/) - ✍️ [Code Examples](https://www.mailslurp.com/examples) - ⚠️ [Report an issue](https://drift.me/mailslurp)  ## Explore  
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailslurp.api.api;

import com.mailslurp.client.ApiException;
import com.mailslurp.models.CreateDomainOptions;
import com.mailslurp.models.DomainPlusVerificationRecordsAndStatus;
import com.mailslurp.models.DomainPreview;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DomainControllerApi
 */
@Ignore
public class DomainControllerApiTest {

    private final DomainControllerApi api = new DomainControllerApi();

    
    /**
     * Create Domain
     *
     * Link a domain that you own with MailSlurp so you can create email addresses using it. Endpoint returns DNS records used for validation. You must add these verification records to your host provider&#39;s DNS setup to verify the domain.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createDomainTest() throws ApiException {
        CreateDomainOptions domainOptions = null;
        DomainPlusVerificationRecordsAndStatus response = api.createDomain(domainOptions);

        // TODO: test validations
    }
    
    /**
     * Delete a domain
     *
     * Delete a domain. This will disable any existing inboxes that use this domain.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteDomainTest() throws ApiException {
        UUID id = null;
        api.deleteDomain(id);

        // TODO: test validations
    }
    
    /**
     * Get a domain
     *
     * Returns domain verification status and tokens for a given domain
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDomainTest() throws ApiException {
        UUID id = null;
        DomainPlusVerificationRecordsAndStatus response = api.getDomain(id);

        // TODO: test validations
    }
    
    /**
     * Get domains
     *
     * List all custom domains you have created
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDomainsTest() throws ApiException {
        List<DomainPreview> response = api.getDomains();

        // TODO: test validations
    }
    
}
